name: CD Container App

on:  
  workflow_dispatch:

permissions: 
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container Image 
        uses: docker/build-push-action@v4
        with:
          load: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ vars.ORGANISATION_NAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          file: ${{ vars.DOCKERFILE_PATH }}
          context: ${{ vars.BUILD_CONTEXT }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"

      - name: Push container image to registry
        id: push-image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ vars.ORGANISATION_NAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          file: ${{ vars.DOCKERFILE_PATH }}
          context: ${{ vars.BUILD_CONTEXT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      
      - name: App Service Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.APP_NAME }}
          app-settings-json: '${{ secrets.APP_SECRETS }}' 

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.APP_NAME }}
          images: ${{ vars.DOCKER_REGISTRY }}/${{ vars.ORGANISATION_NAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}

        
  
  