name: CD Terraform

on:
  workflow_dispatch:

env:
  RUNTIME_ENVIRONMENT: local
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  TF_VAR_administrator_login: ${{ secrets.TF_VAR_administrator_login }}
  TF_VAR_administrator_login_password: ${{ secrets.TF_VAR_administrator_login_password }}

jobs:
  terra-apply:
    name: CD Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Azure
        run:  pip3 install --no-cache-dir -U azure-cli==2.43.0
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@main
        id: setup
          
      - name: Terraform Apply
        id: apply
        run: |
          make terra-apply
      
      
